apiVersion: v1
kind: Service
metadata:
  name: virtual-friends
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32080
  selector:
    app: virtual-friends
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-friends
spec:
  selector:
    matchLabels:
      app: virtual-friends
  template:
    metadata:
      labels:
        app: virtual-friends
    spec:
      containers:
      - name: virtual-friends
        image: websockets-test:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 1
        ports:
        - containerPort: 80
