apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-friends-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-friends
  template:
    metadata:
      labels:
        app: virtual-friends
    spec:
      containers:
      - name: virtual-friends-app
        image: gcr.io/ysong-chat/flask-app:a3ee74e-be294883
        # gcr.io/ysong-chat/flask-app:07c3f63-094e3004
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "10Gi"
            cpu: "2"
            ephemeral-storage: "10Gi"
            nvidia.com/gpu: "1"
          limits:
            memory: "10Gi"
            cpu: "2"
            ephemeral-storage: "10Gi"
            nvidia.com/gpu: "1"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"
#      nodeSelector:
#        nvidia.com/gpu: present