apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-friends-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-friends
  template:
    metadata:
      labels:
        app: virtual-friends
    spec:
      containers:
      - name: virtual-friends-app
        image: gcr.io/ysong-chat/flask-app:c186778-f5a92fe4
        # gcr.io/ysong-chat/flask-app:9ceb988-e2e37dc4
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
            ephemeral-storage: "2Gi"
            nvidia.com/gpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
            ephemeral-storage: "2Gi"
            nvidia.com/gpu: "1"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"
#      nodeSelector:
#        nvidia.com/gpu: present