apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-friends-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-friends
  template:
    metadata:
      labels:
        app: virtual-friends
    spec:
      containers:
      - name: virtual-friends-app
        image: gcr.io/ysong-chat/flask-app:041ea17-16c48230
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "5Gi"
            cpu: "3"
            ephemeral-storage: "5Gi"
#            nvidia.com/gpu: "1" # Requesting 1 T4 GPU
          limits:
            memory: "5Gi"
            cpu: "3"
            ephemeral-storage: "5Gi"
#            nvidia.com/gpu: "1" # Limiting to 1 T4 GPU