apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"virtual-friends-backendconfig"}}'
  name: virtual-friends
spec:
  type: LoadBalancer
  selector:
    app: virtual-friends
  ports:
  - port: 80
    targetPort: 8080
---