// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ws_message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VirtualfriendsProto {

  /// <summary>Holder for reflection information generated from ws_message.proto</summary>
  public static partial class WsMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for ws_message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WsMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChB3c19tZXNzYWdlLnByb3RvEhR2aXJ0dWFsZnJpZW5kc19wcm90byKgAQoJ",
            "VmZSZXF1ZXN0EjEKBGVjaG8YAiABKAsyIS52aXJ0dWFsZnJpZW5kc19wcm90",
            "by5FY2hvUmVxdWVzdEgAEk8KFHN0cmVhbV9yZXBseV9tZXNzYWdlGAYgASgL",
            "Mi8udmlydHVhbGZyaWVuZHNfcHJvdG8uU3RyZWFtUmVwbHlNZXNzYWdlUmVx",
            "dWVzdEgAQgkKB3JlcXVlc3RKBAgBEAIi0AEKClZmUmVzcG9uc2USMAoFZXJy",
            "b3IYASABKAsyIS52aXJ0dWFsZnJpZW5kc19wcm90by5DdXN0b21FcnJvchIy",
            "CgRlY2hvGAIgASgLMiIudmlydHVhbGZyaWVuZHNfcHJvdG8uRWNob1Jlc3Bv",
            "bnNlSAASUAoUc3RyZWFtX3JlcGx5X21lc3NhZ2UYBiABKAsyMC52aXJ0dWFs",
            "ZnJpZW5kc19wcm90by5TdHJlYW1SZXBseU1lc3NhZ2VSZXNwb25zZUgAQgoK",
            "CHJlc3BvbnNlIiQKC0N1c3RvbUVycm9yEhUKDWVycm9yX21lc3NhZ2UYASAB",
            "KAkiGwoLRWNob1JlcXVlc3QSDAoEdGV4dBgBIAEoCSIcCgxFY2hvUmVzcG9u",
            "c2USDAoEdGV4dBgBIAEoCSJTCgtWb2ljZUNvbmZpZxIzCgp2b2ljZV90eXBl",
            "GAEgASgOMh8udmlydHVhbGZyaWVuZHNfcHJvdG8uVm9pY2VUeXBlEg8KB29j",
            "dGF2ZXMYAiABKAIiPQoPTWlycm9yZWRDb250ZW50EhYKDmNoYXJhY3Rlcl9u",
            "YW1lGAEgASgJEhIKCnNlc3Npb25faWQYAiABKAMi9gEKGVN0cmVhbVJlcGx5",
            "TWVzc2FnZVJlcXVlc3QSPwoQbWlycm9yZWRfY29udGVudBgBIAEoCzIlLnZp",
            "cnR1YWxmcmllbmRzX3Byb3RvLk1pcnJvcmVkQ29udGVudBIVCg1qc29uX21l",
            "c3NhZ2VzGAIgAygJEhYKDmN1c3RvbV9wcm9tcHRzGAcgASgJEg0KA3dhdhgD",
            "IAEoDEgAEg4KBHRleHQYBiABKAlIABI3Cgx2b2ljZV9jb25maWcYBSABKAsy",
            "IS52aXJ0dWFsZnJpZW5kc19wcm90by5Wb2ljZUNvbmZpZ0IRCg9jdXJyZW50",
            "X21lc3NhZ2Ui6gEKGlN0cmVhbVJlcGx5TWVzc2FnZVJlc3BvbnNlEj8KEG1p",
            "cnJvcmVkX2NvbnRlbnQYBiABKAsyJS52aXJ0dWFsZnJpZW5kc19wcm90by5N",
            "aXJyb3JlZENvbnRlbnQSFQoNcmVwbHlfbWVzc2FnZRgBIAEoCRIOCgZhY3Rp",
            "b24YAiABKAkSEQoJc2VudGltZW50GAMgASgJEhEKCXJlcGx5X3dhdhgEIAEo",
            "DBIYChB0cmFuc2NyaWJlZF90ZXh0GAUgASgJEhMKC2NodW5rX2luZGV4GAcg",
            "ASgFEg8KB2lzX3N0b3AYCCABKAgqiwEKCVZvaWNlVHlwZRIVChFWb2ljZVR5",
            "cGVfSW52YWxpZBAAEhgKFFZvaWNlVHlwZV9Ob3JtYWxNYWxlEAESGwoXVm9p",
            "Y2VUeXBlX05vcm1hbEZlbWFsZTEQAhIbChdWb2ljZVR5cGVfTm9ybWFsRmVt",
            "YWxlMhADEhMKD1ZvaWNlQ29uZmlnX09yYxAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::VirtualfriendsProto.VoiceType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualfriendsProto.VfRequest), global::VirtualfriendsProto.VfRequest.Parser, new[]{ "Echo", "StreamReplyMessage" }, new[]{ "Request" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualfriendsProto.VfResponse), global::VirtualfriendsProto.VfResponse.Parser, new[]{ "Error", "Echo", "StreamReplyMessage" }, new[]{ "Response" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualfriendsProto.CustomError), global::VirtualfriendsProto.CustomError.Parser, new[]{ "ErrorMessage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualfriendsProto.EchoRequest), global::VirtualfriendsProto.EchoRequest.Parser, new[]{ "Text" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualfriendsProto.EchoResponse), global::VirtualfriendsProto.EchoResponse.Parser, new[]{ "Text" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualfriendsProto.VoiceConfig), global::VirtualfriendsProto.VoiceConfig.Parser, new[]{ "VoiceType", "Octaves" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualfriendsProto.MirroredContent), global::VirtualfriendsProto.MirroredContent.Parser, new[]{ "CharacterName", "SessionId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualfriendsProto.StreamReplyMessageRequest), global::VirtualfriendsProto.StreamReplyMessageRequest.Parser, new[]{ "MirroredContent", "JsonMessages", "CustomPrompts", "Wav", "Text", "VoiceConfig" }, new[]{ "CurrentMessage" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VirtualfriendsProto.StreamReplyMessageResponse), global::VirtualfriendsProto.StreamReplyMessageResponse.Parser, new[]{ "MirroredContent", "ReplyMessage", "Action", "Sentiment", "ReplyWav", "TranscribedText", "ChunkIndex", "IsStop" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Next tag: 3
  /// </summary>
  public enum VoiceType {
    [pbr::OriginalName("VoiceType_Invalid")] Invalid = 0,
    [pbr::OriginalName("VoiceType_NormalMale")] NormalMale = 1,
    [pbr::OriginalName("VoiceType_NormalFemale1")] NormalFemale1 = 2,
    [pbr::OriginalName("VoiceType_NormalFemale2")] NormalFemale2 = 3,
    [pbr::OriginalName("VoiceConfig_Orc")] VoiceConfigOrc = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Next tag: 7
  /// </summary>
  public sealed partial class VfRequest : pb::IMessage<VfRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VfRequest> _parser = new pb::MessageParser<VfRequest>(() => new VfRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VfRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualfriendsProto.WsMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VfRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VfRequest(VfRequest other) : this() {
      switch (other.RequestCase) {
        case RequestOneofCase.Echo:
          Echo = other.Echo.Clone();
          break;
        case RequestOneofCase.StreamReplyMessage:
          StreamReplyMessage = other.StreamReplyMessage.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VfRequest Clone() {
      return new VfRequest(this);
    }

    /// <summary>Field number for the "echo" field.</summary>
    public const int EchoFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VirtualfriendsProto.EchoRequest Echo {
      get { return requestCase_ == RequestOneofCase.Echo ? (global::VirtualfriendsProto.EchoRequest) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.Echo;
      }
    }

    /// <summary>Field number for the "stream_reply_message" field.</summary>
    public const int StreamReplyMessageFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VirtualfriendsProto.StreamReplyMessageRequest StreamReplyMessage {
      get { return requestCase_ == RequestOneofCase.StreamReplyMessage ? (global::VirtualfriendsProto.StreamReplyMessageRequest) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.StreamReplyMessage;
      }
    }

    private object request_;
    /// <summary>Enum of possible cases for the "request" oneof.</summary>
    public enum RequestOneofCase {
      None = 0,
      Echo = 2,
      StreamReplyMessage = 6,
    }
    private RequestOneofCase requestCase_ = RequestOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestOneofCase RequestCase {
      get { return requestCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRequest() {
      requestCase_ = RequestOneofCase.None;
      request_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VfRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VfRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Echo, other.Echo)) return false;
      if (!object.Equals(StreamReplyMessage, other.StreamReplyMessage)) return false;
      if (RequestCase != other.RequestCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (requestCase_ == RequestOneofCase.Echo) hash ^= Echo.GetHashCode();
      if (requestCase_ == RequestOneofCase.StreamReplyMessage) hash ^= StreamReplyMessage.GetHashCode();
      hash ^= (int) requestCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (requestCase_ == RequestOneofCase.Echo) {
        output.WriteRawTag(18);
        output.WriteMessage(Echo);
      }
      if (requestCase_ == RequestOneofCase.StreamReplyMessage) {
        output.WriteRawTag(50);
        output.WriteMessage(StreamReplyMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (requestCase_ == RequestOneofCase.Echo) {
        output.WriteRawTag(18);
        output.WriteMessage(Echo);
      }
      if (requestCase_ == RequestOneofCase.StreamReplyMessage) {
        output.WriteRawTag(50);
        output.WriteMessage(StreamReplyMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (requestCase_ == RequestOneofCase.Echo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Echo);
      }
      if (requestCase_ == RequestOneofCase.StreamReplyMessage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StreamReplyMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VfRequest other) {
      if (other == null) {
        return;
      }
      switch (other.RequestCase) {
        case RequestOneofCase.Echo:
          if (Echo == null) {
            Echo = new global::VirtualfriendsProto.EchoRequest();
          }
          Echo.MergeFrom(other.Echo);
          break;
        case RequestOneofCase.StreamReplyMessage:
          if (StreamReplyMessage == null) {
            StreamReplyMessage = new global::VirtualfriendsProto.StreamReplyMessageRequest();
          }
          StreamReplyMessage.MergeFrom(other.StreamReplyMessage);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            global::VirtualfriendsProto.EchoRequest subBuilder = new global::VirtualfriendsProto.EchoRequest();
            if (requestCase_ == RequestOneofCase.Echo) {
              subBuilder.MergeFrom(Echo);
            }
            input.ReadMessage(subBuilder);
            Echo = subBuilder;
            break;
          }
          case 50: {
            global::VirtualfriendsProto.StreamReplyMessageRequest subBuilder = new global::VirtualfriendsProto.StreamReplyMessageRequest();
            if (requestCase_ == RequestOneofCase.StreamReplyMessage) {
              subBuilder.MergeFrom(StreamReplyMessage);
            }
            input.ReadMessage(subBuilder);
            StreamReplyMessage = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            global::VirtualfriendsProto.EchoRequest subBuilder = new global::VirtualfriendsProto.EchoRequest();
            if (requestCase_ == RequestOneofCase.Echo) {
              subBuilder.MergeFrom(Echo);
            }
            input.ReadMessage(subBuilder);
            Echo = subBuilder;
            break;
          }
          case 50: {
            global::VirtualfriendsProto.StreamReplyMessageRequest subBuilder = new global::VirtualfriendsProto.StreamReplyMessageRequest();
            if (requestCase_ == RequestOneofCase.StreamReplyMessage) {
              subBuilder.MergeFrom(StreamReplyMessage);
            }
            input.ReadMessage(subBuilder);
            StreamReplyMessage = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Next tag: 7
  /// </summary>
  public sealed partial class VfResponse : pb::IMessage<VfResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VfResponse> _parser = new pb::MessageParser<VfResponse>(() => new VfResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VfResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualfriendsProto.WsMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VfResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VfResponse(VfResponse other) : this() {
      error_ = other.error_ != null ? other.error_.Clone() : null;
      switch (other.ResponseCase) {
        case ResponseOneofCase.Echo:
          Echo = other.Echo.Clone();
          break;
        case ResponseOneofCase.StreamReplyMessage:
          StreamReplyMessage = other.StreamReplyMessage.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VfResponse Clone() {
      return new VfResponse(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    private global::VirtualfriendsProto.CustomError error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VirtualfriendsProto.CustomError Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "echo" field.</summary>
    public const int EchoFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VirtualfriendsProto.EchoResponse Echo {
      get { return responseCase_ == ResponseOneofCase.Echo ? (global::VirtualfriendsProto.EchoResponse) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.Echo;
      }
    }

    /// <summary>Field number for the "stream_reply_message" field.</summary>
    public const int StreamReplyMessageFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VirtualfriendsProto.StreamReplyMessageResponse StreamReplyMessage {
      get { return responseCase_ == ResponseOneofCase.StreamReplyMessage ? (global::VirtualfriendsProto.StreamReplyMessageResponse) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.StreamReplyMessage;
      }
    }

    private object response_;
    /// <summary>Enum of possible cases for the "response" oneof.</summary>
    public enum ResponseOneofCase {
      None = 0,
      Echo = 2,
      StreamReplyMessage = 6,
    }
    private ResponseOneofCase responseCase_ = ResponseOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseOneofCase ResponseCase {
      get { return responseCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResponse() {
      responseCase_ = ResponseOneofCase.None;
      response_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VfResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VfResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Error, other.Error)) return false;
      if (!object.Equals(Echo, other.Echo)) return false;
      if (!object.Equals(StreamReplyMessage, other.StreamReplyMessage)) return false;
      if (ResponseCase != other.ResponseCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (error_ != null) hash ^= Error.GetHashCode();
      if (responseCase_ == ResponseOneofCase.Echo) hash ^= Echo.GetHashCode();
      if (responseCase_ == ResponseOneofCase.StreamReplyMessage) hash ^= StreamReplyMessage.GetHashCode();
      hash ^= (int) responseCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (error_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Error);
      }
      if (responseCase_ == ResponseOneofCase.Echo) {
        output.WriteRawTag(18);
        output.WriteMessage(Echo);
      }
      if (responseCase_ == ResponseOneofCase.StreamReplyMessage) {
        output.WriteRawTag(50);
        output.WriteMessage(StreamReplyMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (error_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Error);
      }
      if (responseCase_ == ResponseOneofCase.Echo) {
        output.WriteRawTag(18);
        output.WriteMessage(Echo);
      }
      if (responseCase_ == ResponseOneofCase.StreamReplyMessage) {
        output.WriteRawTag(50);
        output.WriteMessage(StreamReplyMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (error_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (responseCase_ == ResponseOneofCase.Echo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Echo);
      }
      if (responseCase_ == ResponseOneofCase.StreamReplyMessage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StreamReplyMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VfResponse other) {
      if (other == null) {
        return;
      }
      if (other.error_ != null) {
        if (error_ == null) {
          Error = new global::VirtualfriendsProto.CustomError();
        }
        Error.MergeFrom(other.Error);
      }
      switch (other.ResponseCase) {
        case ResponseOneofCase.Echo:
          if (Echo == null) {
            Echo = new global::VirtualfriendsProto.EchoResponse();
          }
          Echo.MergeFrom(other.Echo);
          break;
        case ResponseOneofCase.StreamReplyMessage:
          if (StreamReplyMessage == null) {
            StreamReplyMessage = new global::VirtualfriendsProto.StreamReplyMessageResponse();
          }
          StreamReplyMessage.MergeFrom(other.StreamReplyMessage);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (error_ == null) {
              Error = new global::VirtualfriendsProto.CustomError();
            }
            input.ReadMessage(Error);
            break;
          }
          case 18: {
            global::VirtualfriendsProto.EchoResponse subBuilder = new global::VirtualfriendsProto.EchoResponse();
            if (responseCase_ == ResponseOneofCase.Echo) {
              subBuilder.MergeFrom(Echo);
            }
            input.ReadMessage(subBuilder);
            Echo = subBuilder;
            break;
          }
          case 50: {
            global::VirtualfriendsProto.StreamReplyMessageResponse subBuilder = new global::VirtualfriendsProto.StreamReplyMessageResponse();
            if (responseCase_ == ResponseOneofCase.StreamReplyMessage) {
              subBuilder.MergeFrom(StreamReplyMessage);
            }
            input.ReadMessage(subBuilder);
            StreamReplyMessage = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (error_ == null) {
              Error = new global::VirtualfriendsProto.CustomError();
            }
            input.ReadMessage(Error);
            break;
          }
          case 18: {
            global::VirtualfriendsProto.EchoResponse subBuilder = new global::VirtualfriendsProto.EchoResponse();
            if (responseCase_ == ResponseOneofCase.Echo) {
              subBuilder.MergeFrom(Echo);
            }
            input.ReadMessage(subBuilder);
            Echo = subBuilder;
            break;
          }
          case 50: {
            global::VirtualfriendsProto.StreamReplyMessageResponse subBuilder = new global::VirtualfriendsProto.StreamReplyMessageResponse();
            if (responseCase_ == ResponseOneofCase.StreamReplyMessage) {
              subBuilder.MergeFrom(StreamReplyMessage);
            }
            input.ReadMessage(subBuilder);
            StreamReplyMessage = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Next tag: 2
  /// </summary>
  public sealed partial class CustomError : pb::IMessage<CustomError>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CustomError> _parser = new pb::MessageParser<CustomError>(() => new CustomError());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CustomError> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualfriendsProto.WsMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomError() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomError(CustomError other) : this() {
      errorMessage_ = other.errorMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomError Clone() {
      return new CustomError(this);
    }

    /// <summary>Field number for the "error_message" field.</summary>
    public const int ErrorMessageFieldNumber = 1;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CustomError);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CustomError other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorMessage != other.ErrorMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ErrorMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ErrorMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CustomError other) {
      if (other == null) {
        return;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ErrorMessage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ErrorMessage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Next tag: 2
  /// </summary>
  public sealed partial class EchoRequest : pb::IMessage<EchoRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EchoRequest> _parser = new pb::MessageParser<EchoRequest>(() => new EchoRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EchoRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualfriendsProto.WsMessageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EchoRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EchoRequest(EchoRequest other) : this() {
      text_ = other.text_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EchoRequest Clone() {
      return new EchoRequest(this);
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EchoRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EchoRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EchoRequest other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Next tag: 2
  /// </summary>
  public sealed partial class EchoResponse : pb::IMessage<EchoResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EchoResponse> _parser = new pb::MessageParser<EchoResponse>(() => new EchoResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EchoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualfriendsProto.WsMessageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EchoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EchoResponse(EchoResponse other) : this() {
      text_ = other.text_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EchoResponse Clone() {
      return new EchoResponse(this);
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 1;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EchoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EchoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Text != other.Text) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Text.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Text);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EchoResponse other) {
      if (other == null) {
        return;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Text = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Next tag: 3
  /// </summary>
  public sealed partial class VoiceConfig : pb::IMessage<VoiceConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VoiceConfig> _parser = new pb::MessageParser<VoiceConfig>(() => new VoiceConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VoiceConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualfriendsProto.WsMessageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VoiceConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VoiceConfig(VoiceConfig other) : this() {
      voiceType_ = other.voiceType_;
      octaves_ = other.octaves_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VoiceConfig Clone() {
      return new VoiceConfig(this);
    }

    /// <summary>Field number for the "voice_type" field.</summary>
    public const int VoiceTypeFieldNumber = 1;
    private global::VirtualfriendsProto.VoiceType voiceType_ = global::VirtualfriendsProto.VoiceType.Invalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VirtualfriendsProto.VoiceType VoiceType {
      get { return voiceType_; }
      set {
        voiceType_ = value;
      }
    }

    /// <summary>Field number for the "octaves" field.</summary>
    public const int OctavesFieldNumber = 2;
    private float octaves_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Octaves {
      get { return octaves_; }
      set {
        octaves_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VoiceConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VoiceConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VoiceType != other.VoiceType) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Octaves, other.Octaves)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VoiceType != global::VirtualfriendsProto.VoiceType.Invalid) hash ^= VoiceType.GetHashCode();
      if (Octaves != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Octaves);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VoiceType != global::VirtualfriendsProto.VoiceType.Invalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) VoiceType);
      }
      if (Octaves != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Octaves);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VoiceType != global::VirtualfriendsProto.VoiceType.Invalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) VoiceType);
      }
      if (Octaves != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Octaves);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VoiceType != global::VirtualfriendsProto.VoiceType.Invalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) VoiceType);
      }
      if (Octaves != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VoiceConfig other) {
      if (other == null) {
        return;
      }
      if (other.VoiceType != global::VirtualfriendsProto.VoiceType.Invalid) {
        VoiceType = other.VoiceType;
      }
      if (other.Octaves != 0F) {
        Octaves = other.Octaves;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            VoiceType = (global::VirtualfriendsProto.VoiceType) input.ReadEnum();
            break;
          }
          case 21: {
            Octaves = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            VoiceType = (global::VirtualfriendsProto.VoiceType) input.ReadEnum();
            break;
          }
          case 21: {
            Octaves = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MirroredContent contains the content that is copied from request to response.
  /// Next tag: 3
  /// </summary>
  public sealed partial class MirroredContent : pb::IMessage<MirroredContent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MirroredContent> _parser = new pb::MessageParser<MirroredContent>(() => new MirroredContent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MirroredContent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualfriendsProto.WsMessageReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MirroredContent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MirroredContent(MirroredContent other) : this() {
      characterName_ = other.characterName_;
      sessionId_ = other.sessionId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MirroredContent Clone() {
      return new MirroredContent(this);
    }

    /// <summary>Field number for the "character_name" field.</summary>
    public const int CharacterNameFieldNumber = 1;
    private string characterName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterName {
      get { return characterName_; }
      set {
        characterName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 2;
    private long sessionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MirroredContent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MirroredContent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CharacterName != other.CharacterName) return false;
      if (SessionId != other.SessionId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CharacterName.Length != 0) hash ^= CharacterName.GetHashCode();
      if (SessionId != 0L) hash ^= SessionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CharacterName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CharacterName);
      }
      if (SessionId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SessionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CharacterName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CharacterName);
      }
      if (SessionId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SessionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CharacterName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterName);
      }
      if (SessionId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SessionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MirroredContent other) {
      if (other == null) {
        return;
      }
      if (other.CharacterName.Length != 0) {
        CharacterName = other.CharacterName;
      }
      if (other.SessionId != 0L) {
        SessionId = other.SessionId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CharacterName = input.ReadString();
            break;
          }
          case 16: {
            SessionId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CharacterName = input.ReadString();
            break;
          }
          case 16: {
            SessionId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Next tag: 8
  /// </summary>
  public sealed partial class StreamReplyMessageRequest : pb::IMessage<StreamReplyMessageRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StreamReplyMessageRequest> _parser = new pb::MessageParser<StreamReplyMessageRequest>(() => new StreamReplyMessageRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StreamReplyMessageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualfriendsProto.WsMessageReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StreamReplyMessageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StreamReplyMessageRequest(StreamReplyMessageRequest other) : this() {
      mirroredContent_ = other.mirroredContent_ != null ? other.mirroredContent_.Clone() : null;
      jsonMessages_ = other.jsonMessages_.Clone();
      customPrompts_ = other.customPrompts_;
      voiceConfig_ = other.voiceConfig_ != null ? other.voiceConfig_.Clone() : null;
      switch (other.CurrentMessageCase) {
        case CurrentMessageOneofCase.Wav:
          Wav = other.Wav;
          break;
        case CurrentMessageOneofCase.Text:
          Text = other.Text;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StreamReplyMessageRequest Clone() {
      return new StreamReplyMessageRequest(this);
    }

    /// <summary>Field number for the "mirrored_content" field.</summary>
    public const int MirroredContentFieldNumber = 1;
    private global::VirtualfriendsProto.MirroredContent mirroredContent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VirtualfriendsProto.MirroredContent MirroredContent {
      get { return mirroredContent_; }
      set {
        mirroredContent_ = value;
      }
    }

    /// <summary>Field number for the "json_messages" field.</summary>
    public const int JsonMessagesFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_jsonMessages_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> jsonMessages_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> JsonMessages {
      get { return jsonMessages_; }
    }

    /// <summary>Field number for the "custom_prompts" field.</summary>
    public const int CustomPromptsFieldNumber = 7;
    private string customPrompts_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CustomPrompts {
      get { return customPrompts_; }
      set {
        customPrompts_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "wav" field.</summary>
    public const int WavFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Wav {
      get { return HasWav ? (pb::ByteString) currentMessage_ : pb::ByteString.Empty; }
      set {
        currentMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        currentMessageCase_ = CurrentMessageOneofCase.Wav;
      }
    }
    /// <summary>Gets whether the "wav" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWav {
      get { return currentMessageCase_ == CurrentMessageOneofCase.Wav; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "wav" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWav() {
      if (HasWav) {
        ClearCurrentMessage();
      }
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Text {
      get { return HasText ? (string) currentMessage_ : ""; }
      set {
        currentMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        currentMessageCase_ = CurrentMessageOneofCase.Text;
      }
    }
    /// <summary>Gets whether the "text" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasText {
      get { return currentMessageCase_ == CurrentMessageOneofCase.Text; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "text" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearText() {
      if (HasText) {
        ClearCurrentMessage();
      }
    }

    /// <summary>Field number for the "voice_config" field.</summary>
    public const int VoiceConfigFieldNumber = 5;
    private global::VirtualfriendsProto.VoiceConfig voiceConfig_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VirtualfriendsProto.VoiceConfig VoiceConfig {
      get { return voiceConfig_; }
      set {
        voiceConfig_ = value;
      }
    }

    private object currentMessage_;
    /// <summary>Enum of possible cases for the "current_message" oneof.</summary>
    public enum CurrentMessageOneofCase {
      None = 0,
      Wav = 3,
      Text = 6,
    }
    private CurrentMessageOneofCase currentMessageCase_ = CurrentMessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CurrentMessageOneofCase CurrentMessageCase {
      get { return currentMessageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCurrentMessage() {
      currentMessageCase_ = CurrentMessageOneofCase.None;
      currentMessage_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StreamReplyMessageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StreamReplyMessageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MirroredContent, other.MirroredContent)) return false;
      if(!jsonMessages_.Equals(other.jsonMessages_)) return false;
      if (CustomPrompts != other.CustomPrompts) return false;
      if (Wav != other.Wav) return false;
      if (Text != other.Text) return false;
      if (!object.Equals(VoiceConfig, other.VoiceConfig)) return false;
      if (CurrentMessageCase != other.CurrentMessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (mirroredContent_ != null) hash ^= MirroredContent.GetHashCode();
      hash ^= jsonMessages_.GetHashCode();
      if (CustomPrompts.Length != 0) hash ^= CustomPrompts.GetHashCode();
      if (HasWav) hash ^= Wav.GetHashCode();
      if (HasText) hash ^= Text.GetHashCode();
      if (voiceConfig_ != null) hash ^= VoiceConfig.GetHashCode();
      hash ^= (int) currentMessageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (mirroredContent_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MirroredContent);
      }
      jsonMessages_.WriteTo(output, _repeated_jsonMessages_codec);
      if (HasWav) {
        output.WriteRawTag(26);
        output.WriteBytes(Wav);
      }
      if (voiceConfig_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(VoiceConfig);
      }
      if (HasText) {
        output.WriteRawTag(50);
        output.WriteString(Text);
      }
      if (CustomPrompts.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CustomPrompts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (mirroredContent_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MirroredContent);
      }
      jsonMessages_.WriteTo(ref output, _repeated_jsonMessages_codec);
      if (HasWav) {
        output.WriteRawTag(26);
        output.WriteBytes(Wav);
      }
      if (voiceConfig_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(VoiceConfig);
      }
      if (HasText) {
        output.WriteRawTag(50);
        output.WriteString(Text);
      }
      if (CustomPrompts.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CustomPrompts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (mirroredContent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MirroredContent);
      }
      size += jsonMessages_.CalculateSize(_repeated_jsonMessages_codec);
      if (CustomPrompts.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomPrompts);
      }
      if (HasWav) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Wav);
      }
      if (HasText) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (voiceConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VoiceConfig);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StreamReplyMessageRequest other) {
      if (other == null) {
        return;
      }
      if (other.mirroredContent_ != null) {
        if (mirroredContent_ == null) {
          MirroredContent = new global::VirtualfriendsProto.MirroredContent();
        }
        MirroredContent.MergeFrom(other.MirroredContent);
      }
      jsonMessages_.Add(other.jsonMessages_);
      if (other.CustomPrompts.Length != 0) {
        CustomPrompts = other.CustomPrompts;
      }
      if (other.voiceConfig_ != null) {
        if (voiceConfig_ == null) {
          VoiceConfig = new global::VirtualfriendsProto.VoiceConfig();
        }
        VoiceConfig.MergeFrom(other.VoiceConfig);
      }
      switch (other.CurrentMessageCase) {
        case CurrentMessageOneofCase.Wav:
          Wav = other.Wav;
          break;
        case CurrentMessageOneofCase.Text:
          Text = other.Text;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (mirroredContent_ == null) {
              MirroredContent = new global::VirtualfriendsProto.MirroredContent();
            }
            input.ReadMessage(MirroredContent);
            break;
          }
          case 18: {
            jsonMessages_.AddEntriesFrom(input, _repeated_jsonMessages_codec);
            break;
          }
          case 26: {
            Wav = input.ReadBytes();
            break;
          }
          case 42: {
            if (voiceConfig_ == null) {
              VoiceConfig = new global::VirtualfriendsProto.VoiceConfig();
            }
            input.ReadMessage(VoiceConfig);
            break;
          }
          case 50: {
            Text = input.ReadString();
            break;
          }
          case 58: {
            CustomPrompts = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (mirroredContent_ == null) {
              MirroredContent = new global::VirtualfriendsProto.MirroredContent();
            }
            input.ReadMessage(MirroredContent);
            break;
          }
          case 18: {
            jsonMessages_.AddEntriesFrom(ref input, _repeated_jsonMessages_codec);
            break;
          }
          case 26: {
            Wav = input.ReadBytes();
            break;
          }
          case 42: {
            if (voiceConfig_ == null) {
              VoiceConfig = new global::VirtualfriendsProto.VoiceConfig();
            }
            input.ReadMessage(VoiceConfig);
            break;
          }
          case 50: {
            Text = input.ReadString();
            break;
          }
          case 58: {
            CustomPrompts = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Next tag: 10
  /// </summary>
  public sealed partial class StreamReplyMessageResponse : pb::IMessage<StreamReplyMessageResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StreamReplyMessageResponse> _parser = new pb::MessageParser<StreamReplyMessageResponse>(() => new StreamReplyMessageResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StreamReplyMessageResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VirtualfriendsProto.WsMessageReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StreamReplyMessageResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StreamReplyMessageResponse(StreamReplyMessageResponse other) : this() {
      mirroredContent_ = other.mirroredContent_ != null ? other.mirroredContent_.Clone() : null;
      replyMessage_ = other.replyMessage_;
      action_ = other.action_;
      sentiment_ = other.sentiment_;
      replyWav_ = other.replyWav_;
      transcribedText_ = other.transcribedText_;
      chunkIndex_ = other.chunkIndex_;
      isStop_ = other.isStop_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StreamReplyMessageResponse Clone() {
      return new StreamReplyMessageResponse(this);
    }

    /// <summary>Field number for the "mirrored_content" field.</summary>
    public const int MirroredContentFieldNumber = 6;
    private global::VirtualfriendsProto.MirroredContent mirroredContent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VirtualfriendsProto.MirroredContent MirroredContent {
      get { return mirroredContent_; }
      set {
        mirroredContent_ = value;
      }
    }

    /// <summary>Field number for the "reply_message" field.</summary>
    public const int ReplyMessageFieldNumber = 1;
    private string replyMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ReplyMessage {
      get { return replyMessage_; }
      set {
        replyMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 2;
    private string action_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Action {
      get { return action_; }
      set {
        action_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sentiment" field.</summary>
    public const int SentimentFieldNumber = 3;
    private string sentiment_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Sentiment {
      get { return sentiment_; }
      set {
        sentiment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reply_wav" field.</summary>
    public const int ReplyWavFieldNumber = 4;
    private pb::ByteString replyWav_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ReplyWav {
      get { return replyWav_; }
      set {
        replyWav_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "transcribed_text" field.</summary>
    public const int TranscribedTextFieldNumber = 5;
    private string transcribedText_ = "";
    /// <summary>
    /// will be omitted except the first one.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TranscribedText {
      get { return transcribedText_; }
      set {
        transcribedText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chunk_index" field.</summary>
    public const int ChunkIndexFieldNumber = 7;
    private int chunkIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChunkIndex {
      get { return chunkIndex_; }
      set {
        chunkIndex_ = value;
      }
    }

    /// <summary>Field number for the "is_stop" field.</summary>
    public const int IsStopFieldNumber = 8;
    private bool isStop_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsStop {
      get { return isStop_; }
      set {
        isStop_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StreamReplyMessageResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StreamReplyMessageResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MirroredContent, other.MirroredContent)) return false;
      if (ReplyMessage != other.ReplyMessage) return false;
      if (Action != other.Action) return false;
      if (Sentiment != other.Sentiment) return false;
      if (ReplyWav != other.ReplyWav) return false;
      if (TranscribedText != other.TranscribedText) return false;
      if (ChunkIndex != other.ChunkIndex) return false;
      if (IsStop != other.IsStop) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (mirroredContent_ != null) hash ^= MirroredContent.GetHashCode();
      if (ReplyMessage.Length != 0) hash ^= ReplyMessage.GetHashCode();
      if (Action.Length != 0) hash ^= Action.GetHashCode();
      if (Sentiment.Length != 0) hash ^= Sentiment.GetHashCode();
      if (ReplyWav.Length != 0) hash ^= ReplyWav.GetHashCode();
      if (TranscribedText.Length != 0) hash ^= TranscribedText.GetHashCode();
      if (ChunkIndex != 0) hash ^= ChunkIndex.GetHashCode();
      if (IsStop != false) hash ^= IsStop.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ReplyMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ReplyMessage);
      }
      if (Action.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Action);
      }
      if (Sentiment.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Sentiment);
      }
      if (ReplyWav.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(ReplyWav);
      }
      if (TranscribedText.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TranscribedText);
      }
      if (mirroredContent_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(MirroredContent);
      }
      if (ChunkIndex != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ChunkIndex);
      }
      if (IsStop != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsStop);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ReplyMessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ReplyMessage);
      }
      if (Action.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Action);
      }
      if (Sentiment.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Sentiment);
      }
      if (ReplyWav.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(ReplyWav);
      }
      if (TranscribedText.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TranscribedText);
      }
      if (mirroredContent_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(MirroredContent);
      }
      if (ChunkIndex != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ChunkIndex);
      }
      if (IsStop != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsStop);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (mirroredContent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MirroredContent);
      }
      if (ReplyMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReplyMessage);
      }
      if (Action.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Action);
      }
      if (Sentiment.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sentiment);
      }
      if (ReplyWav.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ReplyWav);
      }
      if (TranscribedText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TranscribedText);
      }
      if (ChunkIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChunkIndex);
      }
      if (IsStop != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StreamReplyMessageResponse other) {
      if (other == null) {
        return;
      }
      if (other.mirroredContent_ != null) {
        if (mirroredContent_ == null) {
          MirroredContent = new global::VirtualfriendsProto.MirroredContent();
        }
        MirroredContent.MergeFrom(other.MirroredContent);
      }
      if (other.ReplyMessage.Length != 0) {
        ReplyMessage = other.ReplyMessage;
      }
      if (other.Action.Length != 0) {
        Action = other.Action;
      }
      if (other.Sentiment.Length != 0) {
        Sentiment = other.Sentiment;
      }
      if (other.ReplyWav.Length != 0) {
        ReplyWav = other.ReplyWav;
      }
      if (other.TranscribedText.Length != 0) {
        TranscribedText = other.TranscribedText;
      }
      if (other.ChunkIndex != 0) {
        ChunkIndex = other.ChunkIndex;
      }
      if (other.IsStop != false) {
        IsStop = other.IsStop;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ReplyMessage = input.ReadString();
            break;
          }
          case 18: {
            Action = input.ReadString();
            break;
          }
          case 26: {
            Sentiment = input.ReadString();
            break;
          }
          case 34: {
            ReplyWav = input.ReadBytes();
            break;
          }
          case 42: {
            TranscribedText = input.ReadString();
            break;
          }
          case 50: {
            if (mirroredContent_ == null) {
              MirroredContent = new global::VirtualfriendsProto.MirroredContent();
            }
            input.ReadMessage(MirroredContent);
            break;
          }
          case 56: {
            ChunkIndex = input.ReadInt32();
            break;
          }
          case 64: {
            IsStop = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ReplyMessage = input.ReadString();
            break;
          }
          case 18: {
            Action = input.ReadString();
            break;
          }
          case 26: {
            Sentiment = input.ReadString();
            break;
          }
          case 34: {
            ReplyWav = input.ReadBytes();
            break;
          }
          case 42: {
            TranscribedText = input.ReadString();
            break;
          }
          case 50: {
            if (mirroredContent_ == null) {
              MirroredContent = new global::VirtualfriendsProto.MirroredContent();
            }
            input.ReadMessage(MirroredContent);
            break;
          }
          case 56: {
            ChunkIndex = input.ReadInt32();
            break;
          }
          case 64: {
            IsStop = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
