service: webapp

runtime: python39  # specify the Python runtime
instance_class: F2  # choose an instance class based on your needs
entrypoint: gunicorn -b :$PORT app:app  # specify the entrypoint for your application

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

env_variables:  # set environment variables
  FLASK_ENV: "production"

handlers:  # specify handlers
- url: /static
  static_dir: static/
- url: /.*
  script: auto
